### ISSUE TITLE
Would you license it under Apache 2.0 and MIT licenses ?

### ISSUE THREAD

**Issue by siriux** [zzoon/libva-rust#1]
Hi @zzoon

I'm interested on support for libva on the rust-media library and playing with libva on other projects. Your work could be helpful, but it would need to be under the Apache 2.0 and MIT licenses to be used there. Would you be willing to distribute it under these licenses?

If so, you can include something like this on the headers or on a LICENSE file:

// Copyright 2017 XXXXXXXXXXXXXXX
//
// Licensed under the Apache License, Version 2.0 <LICENSE-APACHE or
// http://www.apache.org/licenses/LICENSE-2.0> or the MIT license
// <LICENSE-MIT or http://opensource.org/licenses/MIT>, at your
// option. This file may not be copied, modified, or distributed
// except according to those terms.

Here is the issue on the rust-media project.
https://github.com/pcwalton/rust-media/issues/35

Thanks in advance !

**Comment by zzoon** [comment]
Thanks for your interest.
Sure, I'm also considering Apache-2.0 or MIT license for this project.

And about the issue of rust-media, I also appreciate it.
My first goal is integration this project into rust-media, actually. :)

**Comment by siriux** [comment]
That would be great, thanks !
